### ISSUE TITLE
Create a forgot password page

### ISSUE THREAD

**Issue by arpittyagirocks** [arpittyagirocks/LinkUp#1]
Hello Contributors, this is a MERN stack chatting application, its still underdevelopment, can anyone help me making a forgot password page in react.js ?

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by arpittyagirocks** [comment]
I have assigned you the issue @Pulkitxm 
**I am here trying to build a fully functioning social media app and documenting on the way.**
- I have already created two pages [Login Page](https://getlinkup.vercel.app/login) and [Sign up Page](https://getlinkup.vercel.app/signup)
- and this is the [Chatting UI](https://getlinkup.vercel.app). The backend functionalities are also underdevelopment.

> **There is a lot of scope to contribute to this project**
### Forgot password page
You may have a look at the other pages, see the design, maintain the standard, and create a simple forgot password page
Ask me anything you want to know...
